'use client';

import { motion } from 'framer-motion';
import { Building, FileCheck2, Gem, Landmark } from 'lucide-react';
import React from 'react';

const features = [
    {
        title: 'ERC721 Deed Anchors',
        desc: 'The property’s master title is securely logged into an immutable ERC721 non-fungible construct, serving as the definitive legal anchor of physical ownership entirely onchain.',
        icon: Landmark
    },
    {
        title: 'ERC20 Fractionalization',
        desc: 'The ERC721 deed is fractionally split into thousands of fungible ERC20 tokens, opening high-liquidity markets and allowing modern portfolios to diversify in a whole new way.',
        icon: FileCheck2
    },
    {
        title: 'Income Yield Distribution',
        desc: 'Holders of the ERC20 property tokens receive automated, trustless distributions of all net rental income generated by the underlying physical real estate.',
        icon: Gem
    },
    {
        title: 'Perpetual Improvement',
        desc: 'A fractional tax on ERC20 trading volume generates a continuous secondary revenue stream, directly funding physical property upgrades and driving perpetual asset appreciation.',
        icon: Building
    }
];

export default function Features() {
    return (
        <section id="features" className="py-12 relative">
            <div className="max-w-7xl mx-auto px-6">
                <motion.div
                    initial="hidden"
                    whileInView="visible"
                    viewport={{ once: true }}
                    variants={{
                        hidden: { opacity: 0 },
                        visible: {
                            opacity: 1,
                            transition: { staggerChildren: 0.15 }
                        }
                    }}
                    className="grid md:grid-cols-2 lg:grid-cols-4 gap-6"
                >
                    {features.map((item, i) => (
                        <motion.div
                            key={i}
                            variants={{
                                hidden: { opacity: 0, y: 30 },
                                visible: { opacity: 1, y: 0, transition: { duration: 0.6 } }
                            }}
                            className="card !p-0 overflow-hidden flex flex-col group cursor-default"
                        >
                            {/* Icon Header */}
                            <div className="relative w-full aspect-square bg-[#0a1122]/60 border-b border-hr-gold/10 group-hover:border-hr-gold/30 transition-colors flex items-center justify-center">
                                <div className="absolute inset-0 bg-hr-gold opacity-5 blur-[40px] group-hover:opacity-20 transition-opacity duration-500 z-0" />
                                <div className="z-10 group-hover:scale-110 transition-transform duration-700">
                                    {React.createElement(item.icon, { size: 80, strokeWidth: 1, color: '#d4af37' })}
                                </div>
                            </div>
                            
                            {/* Caption Body */}
                            <div className="p-6 text-center flex-grow flex flex-col justify-start pt-8">
                                <h3 className="text-lg font-bold mb-3 text-hr-gold uppercase tracking-wider">{item.title}</h3>
                                <p className="text-gray-400 text-sm leading-relaxed">{item.desc}</p>
                            </div>
                        </motion.div>
                    ))}
                </motion.div>
            </div>
        </section>
    );
}
